version: '3.8'

services:
    web:
        build:
            context: ./
            dockerfile: dev.Dockerfile
        environment:
            - DATABASE_HOST=db
            - DATABASE_USER=postgres
            - DATABASE_PASS=password
        volumes:
            - .:/myapp
        command: ["rails", "s", "-b", "0.0.0.0"]
        ports:
            - 3000:3000
        depends_on:
            - db

    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: docker_rails_development
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgresdb:/var/lib/postgresql/data/

volumes:
    postgresdb: